# Generated by Django 4.1.3 on 2022-11-29 14:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField(unique=True)),
                ('time_period', models.DurationField()),
                ('index', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_per_appointment', models.IntegerField(default=30)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('monday_start', models.TimeField(blank=True, default=datetime.time(7, 0), null=True)),
                ('monday_end', models.TimeField(blank=True, default=datetime.time(22, 0), null=True)),
                ('tuesday_start', models.TimeField(blank=True, default=datetime.time(7, 0), null=True)),
                ('tuesday_end', models.TimeField(blank=True, default=datetime.time(22, 0), null=True)),
                ('wednesday_start', models.TimeField(blank=True, default=datetime.time(7, 0), null=True)),
                ('wednesday_end', models.TimeField(blank=True, default=datetime.time(22, 0), null=True)),
                ('thursday_start', models.TimeField(blank=True, default=datetime.time(7, 0), null=True)),
                ('thursday_end', models.TimeField(blank=True, default=datetime.time(22, 0), null=True)),
                ('friday_start', models.TimeField(blank=True, default=datetime.time(7, 0), null=True)),
                ('friday_end', models.TimeField(blank=True, default=datetime.time(22, 0), null=True)),
                ('saturday_start', models.TimeField(blank=True, default=datetime.time(7, 0), null=True)),
                ('saturday_end', models.TimeField(blank=True, default=datetime.time(22, 0), null=True)),
                ('sunday_start', models.TimeField(blank=True, default=datetime.time(7, 0), null=True)),
                ('sunday_end', models.TimeField(blank=True, default=datetime.time(22, 0), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gap', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointments.gap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.user')),
            ],
        ),
    ]
