# Generated by Django 4.1.3 on 2022-11-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gap',
            name='date_and_time',
            field=models.DateTimeField(),
        ),
    ]
