# Generated by Django 4.1.3 on 2022-11-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_gap_date_and_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gap',
            name='date_and_time',
            field=models.DateTimeField(unique=True),
        ),
    ]
