# Generated by Django 4.1.3 on 2022-12-27 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_gap_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gap',
            name='index',
        ),
    ]
